### ISSUE TITLE
Cheat

### ISSUE THREAD

**Issue by Evelyn-dumbass** [iiDk-the-actual/iis.Stupid.Menu#1]
make it legal :3

**Comment by BrokenSt0ne** [comment]
wawa

**Comment by iiDk-the-actual** [comment]
> make it legal :3

how do i clone a branch i dont wanna make a new repository for 8 lines of code

**Comment by OctoBurr** [comment]
honeslty i dont know 😭  but epik for making ti legeal

**Comment by lunakittyyy** [comment]
> > make it legal :3
> 
> how do i clone a branch i dont wanna make a new repository for 8 lines of code

PhotonNetwork.FindFriends(new string[0]);

**Comment by iiDk-the-actual** [comment]
> > > make it legal :3
> > 
> > 
> > how do i clone a branch i dont wanna make a new repository for 8 lines of code
> 
> `PhotonNetwork.FindFriends(new string[0]);`

PhotonNetwork.DestroyAll();

**Comment by camera12345** [comment]
bad that its a cheat but good that its open source unlike literally every other cheat

**Comment by camera12345** [comment]
sowwy

**Comment by bubzilla** [comment]
anyways just use it in moddeds ;)

**Comment by camera12345** [comment]
im not using it but if I did cheat then I would use this one

**Comment by VampieVR** [comment]
NEIN

**Comment by dyeddaboi** [comment]
also I fixed it

**Comment by camera12345** [comment]
root beer
