### ISSUE TITLE
Just quit already 🙏 

### ISSUE THREAD

**Issue by odinong** [iiDk-the-actual/iis.Stupid.Menu#102]
stop leaking private stuff, ur menu sucks and im gonna touch u violently

**Comment by Flummidill** [comment]
add idiot tag lol

**Comment by iiDk-the-actual** [comment]
Please make valid issues

**Comment by coconutech47** [comment]
> stop leaking private stuff, ur menu sucks and im gonna touch u violently

this menu has 760 mods how does it suck

**Comment by coconutech47** [comment]
and like instead of complaining just get a different menu if it sucks honestly you deserve the idiot tag lol
