### ISSUE TITLE
iis stupid 5.1.1 not working when i join the game, please help lol

### ISSUE THREAD

**Issue by MonkeyModder13** [iiDk-the-actual/iis.Stupid.Menu#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MonkeyModder13** [comment]
my iis stupid mod menue 5.1.1 is not working

**Comment by iiDk-the-actual** [comment]
At least try

**Comment by MonkeyModder13** [comment]
the 5.1.2 works now

**Comment by MonkeyModder13** [comment]
much appreciated, love your mods btw!
