### ISSUE TITLE
The Kick gun Aint working and makes you disapper 

### ISSUE THREAD

**Issue by Stenior1943** [iiDk-the-actual/iis.Stupid.Menu#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Flummidill** [comment]
I made a fix for it on my fork

**Comment by Stenior1943** [comment]
yo @Flummidill theres an issue it still wont work and its detectable if you use lag gun

**Comment by Flummidill** [comment]
ok
