### ISSUE TITLE
how do i get out of watch menu

### ISSUE THREAD

**Issue by thatboyado** [iiDk-the-actual/iis.Stupid.Menu#112]
im stuck in watch menu

**Comment by WombatVr** [comment]
yeah, this happened to me! IIdk just says joysticks with no context. I don't understand what that means! I use the joysticks and it still doesn't work!!!

**Comment by Flummidill** [comment]
You can go into isp/isp_preferences and remove watch menu from the list

**Comment by iiDk-the-actual** [comment]
Hit Q
Use your joysticks to navigate and turn it off
Gorilla Tag/iisStupidMenu/iiMenu_Preferences.txt // Remove the file or remove ;;Watch Menu on first line

**Comment by WombatVr** [comment]
where is ism, don't know where that is. Sorry, I know this is annoying to have to keep coming back to. also, do you mean q on the keyboard, because that doesn't work.

**Comment by shikun-swag** [comment]
i turned on the watch option in menu settings now i cant even open the menu back up:(
