### ISSUE TITLE
Experimental Mod: Better FPS Boost

### ISSUE THREAD

**Issue by coconutech47** [iiDk-the-actual/iis.Stupid.Menu#116]
Ok so I tried out this mod and it's really good but I couldn't turn it off after, it would say it's off but the textures are still really low. I had normal FPS Boost on at the time so I'm not sure if that's the issue. I cleaned my preferences from the ii's stupid menu files I think that fixed it but I haven't tried yet.

**Comment by iiDk-the-actual** [comment]
just turn it off?

**Comment by coconutech47** [comment]
I'm pretty sure I turned off BOTH of the FPS Boosts, lol.
