### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Wacky-Ski-did-bi** [iiDk-the-actual/iis.Stupid.Menu#119]
So, I have all the requirements needed, I have utilla and virus protection off. Whenever I try and boot up gorilla tag it just doesn't work, it's blank, their is zero changes are happening to the game
![Screenshot 2024-12-26 225335](https://github.com/user-attachments/assets/b33e0cbd-6e0b-49f1-8c8d-e51ee69b8f8f)

**Comment by DogeBestWow** [comment]
Yup, same here.

**Comment by iiDk-the-actual** [comment]
Run the installer in the Discord: https://discord.gg/iidk
