### ISSUE TITLE
Game Keeps Crashing

### ISSUE THREAD

**Issue by BlueGuyBoy** [iiDk-the-actual/iis.Stupid.Menu#121]
Okay, so this menu is great and all, but it keeps crashing for me and my friend. It always goes like this: we get into a private lobby or ghost code together, and just chill there (we don't even have to use the mods) eventually, our game will just crash. We have run multiple tests and found that this mod is the problem. We have suspicions that it may be a RAM/Memory problem, but we aren't entirely sure. Due to this issue, we have been unable to just hang in our own private lobby and mod together. This crash comes without warning, and Gorilla Tag will just fully freeze and we will have to go on our PCs and close Gorilla Tag manually. Me and my friend are actively working to try and find the issue, but it may be on the part of the mod, so it would be great if you could try to find the issue as well.

**Comment by iiDk-the-actual** [comment]
Visual mods are resource intensive, try turning any off that you have on and see if that fixes the issue

**Comment by BlueGuyBoy** [comment]
This worked, thanks! (It was Casual Bone ESP)
