### ISSUE TITLE
im stuck in watch menu

### ISSUE THREAD

**Issue by hypix22** [iiDk-the-actual/iis.Stupid.Menu#122]
i cant come out of watch menu do some one else hav this problen or can someone make a tutorial
how to get out

**Comment by hypix22** [comment]
plss some one help

**Comment by hypix22** [comment]
![Screenshot 2024-12-30 164555](https://github.com/user-attachments/assets/48c86ee2-ad49-4001-91f6-ebd693c85ea6)

**Comment by iiDk-the-actual** [comment]
Press Q
