### ISSUE TITLE
OMFGGG

### ISSUE THREAD

**Issue by bubzilla** [iiDk-the-actual/iis.Stupid.Menu#13]
I WITERAWWWYYY HATEEECHUUUUUUU THIS MENUUUU MOTTTHHHERFUCCCKING BANNNNNNEEEEDEDEDDDD MEEEEEEEEEEEEEEEEEE FORRR EIGHT WEEEEEKKKSS YOU SLUTTTT

**Comment by Fredmonster** [comment]
take a chill pill dude
