### ISSUE TITLE
ITS A VIRUS

### ISSUE THREAD

**Issue by VAN1SHD** [iiDk-the-actual/iis.Stupid.Menu#14]
ITS A VIRUS

**Comment by bubzilla** [comment]
literally not 🥵🥵🥵

**Comment by manthatmods** [comment]
![Screenshot 2024-06-10 135521](https://github.com/iiDk-the-actual/iis.Stupid.Menu/assets/164430252/ae844c4e-a536-4c5e-acec-01649c7cd705)
IT IS A VIRUS

**Comment by bubzilla** [comment]
theres literal proof its not like THE ENTIRE SOURCE CODE?!?!
