### ISSUE TITLE
are you fishthedev?

### ISSUE THREAD

**Issue by vibeside** [iiDk-the-actual/iis.Stupid.Menu#17]
i hope not cause they're uploading malware in your name
https://www.nexusmods.com/gorillatag/mods/192

i downloaded the mod and checked the source. all it does is download from their github(fishthedev/barkhost) and download a runtimebroker exe. now, correct me if i'm wrong, that isn't what your mod does.

**Comment by iiDk-the-actual** [comment]
thats not me report for spam
