### ISSUE TITLE
its a malware

### ISSUE THREAD

**Issue by msmkadnjwedhnuaeb** [iiDk-the-actual/iis.Stupid.Menu#18]
its a mallware
![image](https://github.com/iiDk-the-actual/iis.Stupid.Menu/assets/164599724/8570f33a-0a96-45fd-af9e-ef9c5b07e1ba)

**Comment by iiDk-the-actual** [comment]
you're stupid

**Comment by msmkadnjwedhnuaeb** [comment]
bro my pls unban me I will never send that link

________________________________
