### ISSUE TITLE
ratted?

### ISSUE THREAD

**Issue by Existance1** [iiDk-the-actual/iis.Stupid.Menu#22]
is this menu still ratted?

**Comment by WeeJabo** [comment]
it was never ratted in the first case, people just dont understand that gtag mods trigger the anti virus cuz of its obfuscation or smth

**Comment by iiDk-the-actual** [comment]
no

**Comment by bubzilla** [comment]
> it was never ratted in the first case, people just dont understand that gtag mods trigger the anti virus cuz of its obfuscation or smth

its not the obfuscation its that it tampers with gtag i think so windows defender is grumpy
