### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by Fredmonster** [iiDk-the-actual/iis.Stupid.Menu#25]
i am unsure if this is a rat beacuse ive seen a lot of debate and one guy putting it through a scan and it said it had all kinds of viruses on the other hand i have seen lots of people using it ingame and revieving it so is it a virus or not.

**Comment by Ilovecheesburgerz** [comment]
It's just a false positive, I've been using this menu for months now and I didn't get any viruses, I even have a paid anti virus and when doing a full system scan that took me 5 hrs it didn't find anything associated with Ii's stupid menu. Hope that helped :P

**Comment by lazvazxd** [comment]
false positive i've had it for like a month
