### ISSUE TITLE
iis.Stupid.Menu IS MALWARE

### ISSUE THREAD

**Issue by manthatmods** [iiDk-the-actual/iis.Stupid.Menu#26]
THIS IS MALWARE 
![Screenshot 2024-06-10 135521](https://github.com/iiDk-the-actual/iis.Stupid.Menu/assets/164430252/fae5b349-5174-42ff-879b-1db313e33baf)

**Comment by lazvazxd** [comment]
false positive

**Comment by manthatmods** [comment]
> false positive

THIS IS FUCKING MALWARE BITCH

**Comment by lazvazxd** [comment]
> > false positive
> 
> THIS IS FUCKING MALWARE BITCH

been using it for months also used it on a virtual pc without issues also quite immature to swear at someone for trying to help

**Comment by Sammythemaniam** [comment]
It is false positive

**Comment by hacks4life1** [comment]
Its a false positive the same thing happened to Monkemodmanager when somebody put it through the same test .
