### ISSUE TITLE
gui not opening?

### ISSUE THREAD

**Issue by weejabothedev** [iiDk-the-actual/iis.Stupid.Menu#43]
only mods i have is yizzi's cam mod (not ii's) and the menu, should i have anything else?
looked at the UI script and the button i'm supposed to press is \ (backslash), but it's not working.

**Comment by Toto8745** [comment]
try q

**Comment by QuestRiftReality** [comment]
Q opens it, try tab for the camera mod btw.

**Comment by weejabothedev** [comment]
ahh, thanks y'all :)

**Comment by trmgtvr** [comment]
i downloaded it and put it in plugins and i cant open it

**Comment by trmgtvr** [comment]
i tried q

**Comment by coolguy564** [comment]
when i click the side trigger on my left controller nothing happens
