### ISSUE TITLE
Invisible Monkey and New Gamemode

### ISSUE THREAD

**Issue by QuestRiftReality** [iiDk-the-actual/iis.Stupid.Menu#44]
Lemming somehow broke Invisible Monkey, your arms still move but your torso is frozen and you don't move, I guess a way to patch it is reusing Ghost Monkey but teleporting the player high up then activating Ghost Monkey and teleporting them back down (Might be detected in a future/current update because they're teleporting so far in under a second, not sure.). Also you should make mods for the new game mode, because tag all doesn't work, but Casual Bone ESP lets us see them, might want to make a separate one though. Also when the game mode is gone you should probably make a mod that brings it back for all ii users, basically making a modded lobby that people can connect to if they select the game mode, could be simple. Reuse the infection game mode but make it so if someone is lava monkey simply change their textures and whenever a footstep sound plays from one of them all that white particle. Also not sure if it's platforms or not but footsteps are loud. Sadly 420 will be short lived if you update it.

**Comment by iiDk-the-actual** [comment]
Fixing
