### ISSUE TITLE
cant download because of virus detected

### ISSUE THREAD

**Issue by pikachu123298** [iiDk-the-actual/iis.Stupid.Menu#47]
I have disabled my antivirus but still wont download I need help pls.

**Comment by DogeWasFound** [comment]
latest version has trojan, try 4.0.0

**Comment by iiDk-the-actual** [comment]
turn off your antivirus

**Comment by pikachu123298** [comment]
i did..

**Comment by bubzilla** [comment]
> latest version has trojan, try 4.0.0

the entire source code says otherwise sherlock
