### ISSUE TITLE
нечего нет

### ISSUE THREAD

**Issue by clef239** [iiDk-the-actual/iis.Stupid.Menu#51]
когда установил все по инструкции нечего не происходит , будто я нечего не устанавливал, q не работает

**Comment by iiDk-the-actual** [comment]
Откройте папку BepInEx, перейдите в config и замените текст в BepInEx.cfg на этот: https://pastebin.com/raw/rhr2Tani
Open your BepInEx folder, move to config, and replace the text in BepInEx.cfg with this: https://pastebin.com/raw/rhr2Tani

**Comment by meow393** [comment]
![Image](https://github.com/user-attachments/assets/6a843161-0828-483b-8be7-310a9165dcd9)
