### ISSUE TITLE
a mod

### ISSUE THREAD

**Issue by Toto8745** [iiDk-the-actual/iis.Stupid.Menu#57]
maybe like for the fonts maybe a custom font? like you drop the font into      C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag\iisStupidMenu and it puts the font in the menu with a mod: Custom menu font.

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Toto8745** [comment]
the URL no workie
