### ISSUE TITLE
this is a virus

### ISSUE THREAD

**Issue by flamingdevelopers** [iiDk-the-actual/iis.Stupid.Menu#68]
just a ti worker virus (thank god for mcafee)

**Comment by Flummidill** [comment]
its not

**Comment by bubzilla** [comment]
its not trust me ive read the entire source code before

**Comment by bvodntmiss** [comment]
just because the source code says its not a virus he could have embedded a virus in the dll file the source code means nothing in this situation but the menu is not a virus

**Comment by bubzilla** [comment]
> just because the source code says its not a virus he could have embedded a virus in the dll file the source code means nothing in this situation but the menu is not a virus

d-d-d-d-d-d-d-d-d-d-d-d- DNSPYYYYYYYYYYYYY AAAAAAAAAAAAAAAAAAA

**Comment by Erik2YT** [comment]
Mcafee is the worst AV i know

**Comment by bubzilla** [comment]
> Mcafee is the worst AV i know

real
