### ISSUE TITLE
Add Left Joystick to Rope Control [J]

### ISSUE THREAD

**Issue by Flummidill** [iiDk-the-actual/iis.Stupid.Menu#69]
Add the Left Joystick to the rope control to make it able to rotate the 2Daxis the right joystick uses.
This would allow you to make the robe go in any direction instead of only left right up and down.

**Comment by PaddyCake16** [comment]
how to install the menu?

**Comment by Flummidill** [comment]
look at one of the hundreds of videos that tell you how

**Comment by PaddyCake16** [comment]
no like i install it but there no menu

**Comment by PaddyCake16** [comment]
patch this glitch you can turn on admin stuff by going to search bar and turning it on
