### ISSUE TITLE
Accessing Admin Mods through mod search

### ISSUE THREAD

**Issue by randomguyorsomething** [iiDk-the-actual/iis.Stupid.Menu#70]
**Describe the bug**
This may not be the place to say this, but i really hope this does NOT go to the wrong people in some way, i really want this fixed and it to not be abused.
basically, you can access the admin-only mods using the search button where you search for mods.

**To Reproduce**
1. Click the search button
2. search "admin"
3. see the admin mods (ALSO THEY DO WORK IF YOU CLICK THEM)

**Expected behavior**
well i didnt really expect anything related to admin mods to be shown to me. this bug was found by me wanting to find the rope mods using search and i found something with "admin" infront of the name for the mod, then i went a bit deeper.

**Screenshots**
![image](https://github.com/user-attachments/assets/3569db94-10bd-4c5b-8221-c740b2eee078)

**Desktop (please complete the following information):**
 - Version 4.6.0
 
**Additional context**
i really want this fixed soon, i really dont want this to be abused anywhere.

**Comment by randomguyorsomething** [comment]
something you could do to fix it is make admin mods not searchable.

**Comment by iiDk-the-actual** [comment]
Admin mods can be enabled, but not used. I will make it so the admin mods get deleted if not allowed.
