### ISSUE TITLE
remote access trojan

### ISSUE THREAD

**Issue by peteypocalypse** [iiDk-the-actual/iis.Stupid.Menu#82]
when i put into virustotal it says a trojan gamehack many people know this is a RAT (aka remote access trojan) im not sure if its ii's problem but no matter what it must be fixed as many people use this menu

**Comment by Longno12** [comment]
You are pretty dumb read the false positive again and think of the word gamehack  which you even said and there you will find your answer

**Comment by bubzilla** [comment]
lil bro doesn't know what source code is 🙏
