### ISSUE TITLE
I enabled long menu and now the mod menu is glitched, i cant click any buttons anymore in the mod menu, please fix this.

### ISSUE THREAD

**Issue by DevvPix** [iiDk-the-actual/iis.Stupid.Menu#88]
For some reason, when i enabled long menu, i cant enable any mods now.
i have the 3D mod menu layout.

**Comment by Grimez8-34** [comment]
Me too, I accidently enabled extra long stick long arms and I cant seem to turn it off or use any other mods as a matter of fact! Have you found a solution if so please tell me.
