### ISSUE TITLE
Menu Not Opening?

### ISSUE THREAD

**Issue by LavaBiteYT** [iiDk-the-actual/iis.Stupid.Menu#91]
Menu won't pull out

**Comment by bubzilla** [comment]
give more context, like did you enable watch menu?

**Comment by Flummidill** [comment]
Try copying the iis stupid Menu folder somewhere Else and Remove it from Gorilla Tag folder then thy restarting game

**Comment by LavaBiteYT** [comment]
i just realized none of my mods are working

**Comment by LavaBiteYT** [comment]
> give more context, like did you enable watch menu?

No

**Comment by bubzilla** [comment]
> > give more context, like did you enable watch menu?
> 
> No

that's not context...
