### ISSUE TITLE
lag when using soundboard

### ISSUE THREAD

**Issue by malemeno** [iiDk-the-actual/iis.Stupid.Menu#94]
There is extreme lag at the start and end of the sound

**To Reproduce**
use the soundboard
**Expected behavior**
no lag

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [all]

**Comment by iiDk-the-actual** [comment]
Larger audios take longer times to load

**Comment by malemeno** [comment]
oh ok
